version: '2'

services:
  app:
    image: 'spring-boot-docker:latest'
    build:
      context: .
    ports:
      - 8383:8383
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_HOST=db
      - SPRING_DATASOURCE_USERNAME=SEGUNI
      - SPRING_DATASOURCE_PASSWORD=SEGUNI
      - SPRING_DATASOURCE_PORT=1522
          
  db:
    image: 'gvenzl/oracle-xe:latest'
    container_name: db
    ports:
      - 1522:1521
    environment:
      - ORACLE_USER=SYSTEM
      - ORACLE_PASSWORD=ktalan30